services:
  loopvt:
    image: loop:latest
    container_name: loom-loop-virtual-thread
    ports:
      - "8999:8999"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "VT"
  looptp:
    image: loop:latest
    container_name: loom-loop-thread-pool
    ports:
      - "8998:8998"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "TP"
  loomclientvt:
    image: loom-client:latest
    container_name: loom-io-client-virtual-thread
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "VT"
    depends_on:
      - loomservervt
  loomclienttp:
    image: loom-client:latest
    container_name: loom-io-client-thread-pool
    ports:
      - "8079:8079"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "TP"
    depends_on:
      - loomservertp
  loomservervt:
    image: loom-server:latest
    container_name: loom-io-server-virtual-thread
    ports:
      - "8099:8099"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "VT"
      PORT: "8099"
  loomservertp:
    image: loom-server:latest
    container_name: loom-io-server-thread-pool
    ports:
      - "8098:8098"
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
    environment:
      FLOW: "TP"
      PORT: "8098"
